//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoseGardener.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoseGardenerEntities : DbContext
    {
        public RoseGardenerEntities()
            : base("name=RoseGardenerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<RoseBush> RoseBushes { get; set; }
        public DbSet<RoseGarden> RoseGardens { get; set; }
        public DbSet<Selection> Selections { get; set; }
        public DbSet<Color> Colors { get; set; }
    }
}
