//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoseGardener.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoseGarden
    {
        public RoseGarden()
        {
            this.Selections = new HashSet<Selection>();
        }
    
        public int Id { get; set; }
        public double Width { get; set; }
        public double Length { get; set; }
        public double SquareFootage { get; set; }
        public Nullable<int> Person_Id { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Selection> Selections { get; set; }
    }
}
